#!/bin/sh

uci set luci.main.lang=zh_cn
uci commit luci

uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

uci set dropbear.@dropbear[0].PasswordAuth="on"
uci set dropbear.@dropbear[0].RootPasswordAuth="on"
uci commit dropbear

chmod 700 /etc/dropbear

ln -sf /sbin/ip /usr/bin/ip

sed -i '/option disabled/d' /etc/config/wireless
sed -i '/set wireless.radio${devidx}.disabled/d' /lib/wifi/mac80211.sh
sed -i '/network\/wireless/,+3d' /usr/lib/lua/luci/controller/admin/network.lua

# [ "$(uci -q get network.lan.ipaddr)" = "192.168.2.1" ] && exit 0
# uci set network.lan.ipaddr=192.168.2.1
# uci commit network











exit 0
